experiments: experiments.o sorts.o array_util.o
	gcc -Wall experiments.o sorts.o array_util.o -o experiments

sorts.o: sorts.c 
	gcc -Wall -c sorts.c

array_util.o: array_util.c
	gcc -Wall -c array_util.c

experiments.o: experiments.c
	gcc -Wall -c experiments.c